### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by AlinaIlnitskaya** [Liraley/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Templar-Assassin** [comment]
<h2>Résumé</h2>

<p>&mdash; I always thought that my work itself would tell everything about me, but now it suddenly turns out that it tells people about something completely unknown to me ...</p>
