### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by AlinaIlnitskaya** [Liraley/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Templar-Assassin** [comment]
<h1 class = "name">Lana Del Rey</h1>
<div class = "job">Musician</div>
<ul class = "contacts">
<li>
<a href="https://www.instagram.com/lanadelrey/?hl=ru" rel = "author" class = "instagram">lanadelrey
</a>
</li>

<li>
<a href="https://ru-ru.facebook.com/lanadelrey/" rel = "author" class = "facebook">Lana Del Rey
</a>
</li>
<li>
<a href="https://twitter.com/lanadelrey" rel = "author" class = "twitter">Lana Del Rey
</a>
</li>

</ul>
