### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by AlinaIlnitskaya** [Liraley/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Templar-Assassin** [comment]
EXPERIENCE
2011 - Del Rey uploaded self-made music videos for her songs "Video Games" and "Blue Jeans" to YouTube, featuring vintage footage interspersed with shots of her singing on her webcam.
2012  - Born to Die was released worldwide, and reached number one in 11 countries, though critical reaction was divided.
2013 -  Del Rey filmed Tropico, a musical short film paired to tracks from Paradise, directed by Anthony Mandler. Del Rey screened the film on December 4, 2013 at the Cinerama Dome in Hollywood.
2014 -  Del Rey released a cover of "Once Upon a Dream" for the 2014 dark fantasy film Maleficent.
2015 - Del Rey executive produced a short film Hi, How Are You Daniel Johnston, documenting the life of singer-songwriter Daniel Johnston.
2016 - Del Rey premiered a music video for the song "Freak" from Honeymoon at the Wiltern Theatre in Los Angeles.
2017 - Del Rey's fifth studio album, Lust for Life, was released.
2019 - Del Rey presented filmmaker Guillermo del Toro with his star on the Hollywood Walk of Fame, and subsequently released a cover of "Season of the Witch" for his film, Scary Stories to Tell in the Dark.
2020 - Del Rey will self-publish a book of poetry Violet Bent Backwards Over The Grass and release a corresponding spoken word album.
