### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by AlinaIlnitskaya** [Liraley/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Templar-Assassin** [comment]
**AWARDS**
ASCAP Pop Music Awards
Billboard
Billboard Mid-Year Music Awards
Billboard Women in Music
ECHO Awards
Norway GAFFA Awards
GQ Men of the Year Awards

**LIFE & EDUCATION**
I went to a Catholic school. Sang in the church choir. Studied at a Kent school. Fordham University.

MUSICAL STYLE
Pop,rock, dream pop or baroque pop, indie pop , psychedelic rock, indie music,trip hop,hip hop,lo-fi,trap

**FILMOGRAPHY**
Poolside (2010)
National Anthem (2012)
Ride (2012)
Tropico (2013)
Hi, How Are You Daniel Johnston? (2015)
Freak (2016)
Tower of Song: A Memorial Tribute to Leonard Cohen (2017)
The Kacey Musgraves Christmas Show (2019)
Norman Fucking Rockwell (2019)

**LANGUAGES**
English

**SKILLS**
Write songs and music, dance

**CHARACTER**
Loving, impulsive, dreamy, kind

**LIFE LESSON**
No matter how many people give me advice. I will do what my heart tells me to do.

**LIKES **
I love reality shows. Favorite - Real Housewives
To play guitar
Sad songs
Chocolate and milk

**DISLIKES**
spend money
Lady Gaga
The scene
sharks

**WANTS**
I want to win a Grammy and Golden Globe Award
